version: '3.7'
services:
  mgdb:
    image: mongo:latest
    restart: always
    volumes:
      - /home/muhammad/Dev/Company/nurtw-api/storage/mongo:/data/db/
    networks:
      - myNet
      
  users:
    build: ./users
    restart: always
    networks:
      - myNet
    ports:
      - 3000:3000
  drivers:
    build: ./drivers
    restart: always
    networks:
      - myNet
    ports:
      - 3001:3000
  parcels:
    build: ./parcels
    restart: always
    networks:
      - myNet
    ports:
      - 3002:3000
  parks:
    build: ./parks
    restart: always
    networks:
      - myNet
    ports:
      - 3003:3000
  passengers:
    build: ./passengers
    restart: always
    networks:
      - myNet
    ports:
      - 3004:3000
  vehicles:
    build: ./vehicles
    restart: always
    networks:
      - myNet
    ports:
      - 3005:3000
  # proxy:


networks:
  myNet: