version: '3.7'
services:
  mgdb:
    image: mongo:latest
    restart: always
    volumes:
      - /home/muhammad/Dev/Company/nurtw-api/storage/mongo:/data/db/
    networks:
      - myNet
      
  auth:
    build: ./auth
    restart: always
    # ports:
    #   - 3000:3000
    labels:
      - traefik.frontend.rule=Host:auth.localhost 
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=nurtw-api_myNet
    networks:
      - myNet


  drivers:
    build: ./drivers
    restart: always
    # ports:
    #   - 3001:3000
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=nurtw-api_myNet
    networks:
      - myNet


  parcels:
    build: ./parcels
    restart: always
    # ports:
    #   - 3002:3000
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=nurtw-api_myNet
    networks:
      - myNet


  parks:
    build: ./parks
    restart: always
    # ports:
    #   - 3003:3000
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=nurtw-api_myNet
    networks:
      - myNet


  passengers:
    build: ./passengers
    restart: always
    # ports:
    #   - 3004:3000
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=nurtw-api_myNet
    networks:
      - myNet


  vehicles:
    build: ./vehicles
    restart: always
    # ports:
    #   - 3005:3000
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=nurtw-api_myNet
    networks:
      - myNet


  proxy:
    image: traefik:1.7.6-alpine
    restart: always
    command: --docker
    labels:
      - traefik.frontend.rule=Host:localhost
      - traefik.enable=true
      - traefik.port=8080
      - traefik.docker.network=nurtw-api_myNet
    volumes:
      - /home/muhammad/Dev/Company/nurtw-api/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - myNet


networks:
  myNet: