defaultEntryPoints = ["http"]
logLevel = "INFO"
sendAnonymousUsage = true

[docker]
endpoint = "unix://var/run/docker.sock"
exposedByDefault = false

[api]
dashboard = true
entryPoint = "dashboard"


[entryPoints]
    [entryPoints.dashboard]
        address = ":8080"
    [entryPoint.http]
        address = ":80"
